/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface QueryResult {
  variables: Array<string>
  rows: Array<any>
  rowCount: number
}

export declare class GraphLiteDB {
  /** Open or create a GraphLite database at the given path. */
  static open(path: string): GraphLiteDB
  /** Create a new session for the given username. */
  createSession(username: string): GraphLiteSession
  /** Close the database. */
  close(): void
}

export declare class GraphLiteSession {
  /**
   * Execute a GQL query and return results.
   *
   * Returns an object with `variables`, `rows`, and `rowCount`.
   */
  query(gql: string): QueryResult
  /**
   * Execute a GQL statement without returning results.
   *
   * Use for DDL (CREATE SCHEMA, CREATE GRAPH) and DML (INSERT) statements.
   */
  execute(gql: string): void
  /** Close this session. */
  close(): void
}
